version: "3"

networks:
  metrics:
    external: false
  host:
    external: true

services:

  influxdb:
    image: arm32v7/influxdb:latest
    container_name: influxdb
    restart: always
    #networks: [metrics]
    ports:
      - "8086:8086"
    volumes:
      - $HOME/docker-volume/influxdb/data:/var/lib/influxdb
      - $HOME/docker-volume/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - $HOME/docker-volume/influxdb/init:/docker-entrypoint-initdb.d
    environment:
      - INFLUXDB_ADMIN_USER={{influxUsername}}
      - INFLUXDB_ADMIN_PASSWORD={{influxPassword}}

  telegraf:
    image: telegraf:latest
    restart: always
    container_name: telegraf
    #networks: [metrics]
    volumes:
      - $HOME/docker-volume/influxdb/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  chronograf:
    container_name: chronograf
    restart: always
    image: chronograf:latest
    ports:
      - "8888:8888"
    depends_on:
      - influxdb
    #networks: [metrics,host]
    environment:
      - INFLUXDB_URL=http://influxdb:8086 # needs to match container_name
      - INFLUXDB_USERNAME={{influxUsername}}
      - INFLUXDB_PASSWORD={{influxPassword}}

  portainer:
    container_name: portainer
    restart: always
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/docker-volume/portainer/data:/data
  
  mosquitto:
    container_name: mosquitto
    restart: always
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - $HOME/docker-volume/mosquitto:/mosquitto/
    
 
#https://raw.githubusercontent.com/EddieDSuza/techwitheddie/main/UltimateHomekitHub
#https://blog.anoff.io/2020-12-run-influx-on-raspi-docker-compose/