- name: check if docker is running
  tags:
    - compose
  shell: 'systemctl status docker | grep Active:'
  register: dockerdrunning
  ignore_errors: true

- name: check if docker-compose is installed
  tags:
    - compose
  shell: which docker-compose
  register: dockercomposecheck
  ignore_errors: true
  changed_when:
    - dockercomposecheck.rc == 127 or dockercomposecheck.rc == 0

- name: structure docker directory parsing templates locally
  tags:
    - compose
    - dirsetup
  delegate_to: localhost
  become: false
  when: dockerdrunning.stdout.find('running') != -1 and dockercomposecheck.rc == 0
  block:
    - name: create temporary directory
      tempfile:
        state: directory
      register: tempdir
    - debug:
        var: tempdir.path
    - name: setup internal dirs
      when: item.state == 'directory'
      file:
        state: directory
        dest: '{{ tempdir.path }}/{{ item.path }}'
      with_filetree: docker
    - name: template each file in docker directory
      when: item.state == 'file'
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: "{{ tempdir.path }}/{{ item.path }}"
        force: true
      with_filetree: docker

- name: copy to test folder
  tags:
    - compose
    - dirsetup
  ansible.builtin.copy:
    src: "{{ tempdir.path }}/"
    dest: /home/glados/docker
    follow: yes
    force: true
    owner: glados
    group: glados

- name: Remove temporary directory
  tags:
    - compose
    - dirsetup
  delegate_to: localhost
  become: false
  file:
    state: absent
    path: "{{ tempdir.path }}"


- name: setup directories for volumes
  tags:
    - compose
    - dirsetup
  when: dockerdrunning.stdout.find('running') != -1 and dockercomposecheck.rc == 0
  file:
    path: "{{item}}"
    state: directory
    owner: glados
    group: glados
  loop:
    - /home/glados/docker/volume/authelia
    - /home/glados/docker/volume/authelia/logs
    - /home/glados/docker/volume/influxdb
    - /home/glados/docker/volume/mosquitto
    - /home/glados/docker/volume/portainer
    - /home/glados/docker/volume/traefik
    - /home/glados/docker/volume/uptime-kuma
    - /home/glados/docker/volume/securityalerts

# - name: init glados compose stack
#   tags:
#     - compose
#   when: dockerdrunning.stdout.find('running') != -1 and dockercomposecheck.rc == 0
#   become: true
#   become_user: glados
#   community.docker.docker_compose:
#     project_src: /home/glados/docker/compose/glados
#     remove_orphans: true
#     # recreate: "always"
#   register: composeout


# - name: init iot compose stack
#   tags:
#     - compose
#   when: dockerdrunning.stdout.find('running') != -1 and dockercomposecheck.rc == 0
#   become: true
#   become_user: glados
#   community.docker.docker_compose:
#     project_src: /home/glados/docker/compose/iot
#     remove_orphans: true
