- name: check if docker is running
  tags:
    - compose
  shell: 'systemctl status docker | grep Active:'
  register: dockerdrunning
  ignore_errors: true

- name: check if docker-compose is installed
  tags:
    - compose
  shell: which docker-compose
  register: dockercomposecheck
  ignore_errors: true
  changed_when:
    - dockercomposecheck.rc == 127 or dockercomposecheck.rc == 0

- name: copy docker setup files to docker volume 
  tags:
    - compose
  when: dockerdrunning.stdout.find('running') != -1 and dockercomposecheck.rc == 0
  copy:
    src: compose/volume/
    dest: /home/glados/docker-volume/
    force: true
    owner: glados
    group: glados

- name: setup directories
  tags:
    - compose
  when: dockerdrunning.stdout.find('running') != -1 and dockercomposecheck.rc == 0
  file:
    path: /home/glados/dockercompose/glados/
    state: directory
    owner: glados
    group: glados

- name: copy docker compose file for glados stack
  tags:
    - compose
  when: dockerdrunning.stdout.find('running') != -1 and dockercomposecheck.rc == 0
  ansible.builtin.template:
    src: compose/glados-stack.yml
    dest: /home/glados/dockercompose/glados/docker-compose.yml
    force: true
    owner: glados
    group: glados

- name: setup authelia directory
  tags:
    - compose
    - authelia
  when: dockerdrunning.stdout.find('running') != -1 and dockercomposecheck.rc == 0
  file:
    path: /home/glados/docker-volume/authelia
    state: directory
    owner: glados
    group: glados

- name: copy authelia core config file
  tags:
    - compose
    - authelia
  when: dockerdrunning.stdout.find('running') != -1 and dockercomposecheck.rc == 0
  ansible.builtin.template:
    src: other/authelia/configuration.yml
    dest: /home/glados/docker-volume/authelia/configuration.yml
    force: true
    owner: glados
    group: glados

- name: copy authelia users database config file
  tags:
    - compose
    - authelia
  when: dockerdrunning.stdout.find('running') != -1 and dockercomposecheck.rc == 0
  ansible.builtin.template:
    src: other/authelia/users_database.yml
    dest: /home/glados/docker-volume/authelia/users_database.yml
    force: true
    owner: glados
    group: glados

- name: setup traefik directory
  tags:
    - compose
    - traefik
  when: dockerdrunning.stdout.find('running') != -1 and dockercomposecheck.rc == 0
  file:
    path: /home/glados/docker-volume/traefik
    state: directory
    owner: glados
    group: glados

- name: copy traefik main config file
  tags:
    - compose
    - traefik
  when: dockerdrunning.stdout.find('running') != -1 and dockercomposecheck.rc == 0
  ansible.builtin.template:
    src: other/traefik/traefik.yml
    dest: /home/glados/docker-volume/traefik/traefik.yml
    force: true
    owner: glados
    group: glados

- name: copy traefik external config file
  tags:
    - compose
    - traefik
  when: dockerdrunning.stdout.find('running') != -1 and dockercomposecheck.rc == 0
  ansible.builtin.template:
    src: other/traefik/external.yml
    dest: /home/glados/docker-volume/traefik/external.yml
    force: true
    owner: glados
    group: glados

- name: init compose stack
  tags:
    - compose
  when: dockerdrunning.stdout.find('running') != -1 and dockercomposecheck.rc == 0
  become: true
  become_user: glados
  community.docker.docker_compose:
    project_src: /home/glados/dockercompose/glados
    recreate: "always"
  register: composeout
