- name: Update packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install essential packages
  package: 
    name: "{{ packages }}"
    state: latest

- name: Disable SSH password auth
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication no"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Enable passwordless sudo for "{{ username }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^{{ username }} ALL=(ALL) NOPASSWD: ALL" # acho que isso daqui tem que ser substituido por glados
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"


- name: Restart SSH Daemon
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed