global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

# (Optional) Log information
# ---
log:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: json  # common, json, logfmt
  filePath: /etc/traefik/logs.json

# (Optional) Accesslog
# ---
accesslog:
  format: json  # common, json, logfmt
  filePath: /etc/traefik/access.json

# (Optional) Enable API and Dashboard
# ---
api:
 dashboard: false  # true by default
 insecure: false  # Don't do this in production!

# Entry Points configuration
# ---
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    # tls:
    #   enabled: true
    address: :443

# Configure your CertificateResolver here...
# ---
certificatesResolvers:
  staging:
    acme:
      email: pedrohenriqueff@gmail.com
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: dynu

  production:
    acme:
      email: pedrohenriqueff@gmail.com
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: dynu
        
providers:
  docker:
    exposedByDefault: false  # Default is true
  file:
    # watch for dynamic configuration changes
    directory: /traefik/files
    watch: true