input:
  label: "idk"
  mqtt:
    urls:
      - 192.168.15.18:1883
    topics:
      - /home/bedroom/sensors/temperature
    client_id: "glados-benthos"
# pipeline:
output:
  label: "what"
  http_client:
    url: "http://192.168.15.18:8086/write?db=sensors"
    headers:
      Authorization: Token USER:PASS
    successful_on: [200]



# curl -i -XPOST 'http://localhost:8086/api/v2/write?bucket=db/rp&precision=ns' \
#   --header 'Authorization: Token username:password' \
#   --data-raw 'cpu_load_short,host=server01,region=us-west value=0.64 1434055562000000000'
# room value=25.3
